name: directus

services:
  postgis:
    extends:
      file: ./docker-compose-postgis.yml
      service: postgis

  redis:
    extends:
      file: ./docker-compose-redis.yml
      service: redis
  
  directus:
    extends:
      file: ./docker-compose-directus.yml
      service: directus
    depends_on:
      postgis:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgis_data:
  redis_data:
